//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemanticProcessor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class SemanticServer : global::System.Configuration.ApplicationSettingsBase {
        
        private static SemanticServer defaultInstance = ((SemanticServer)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SemanticServer())));
        
        public static SemanticServer Default {
            get {
                return defaultInstance;
            }
        }
    }
}
