//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemanticProcessor.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SemSerRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SemSerRes() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SemanticProcessor.Properties.SemSerRes", typeof(SemSerRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Command: {0}. The current token is {1} is replaced by the {2} token.
        /// </summary>
        internal static string logAssignToken {
            get {
                return ResourceManager.GetString("logAssignToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The debug log is disabled.
        /// </summary>
        internal static string logDisabled {
            get {
                return ResourceManager.GetString("logDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The command was not found.
        /// </summary>
        internal static string logErrCmdNotFound {
            get {
                return ResourceManager.GetString("logErrCmdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ERR Telegram is invalid.
        /// </summary>
        internal static string logErrTlgrmInvalid {
            get {
                return ResourceManager.GetString("logErrTlgrmInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a token mismatch.
        /// </summary>
        internal static string logErrTockenMismatch {
            get {
                return ResourceManager.GetString("logErrTockenMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Can ShutDown = {0}.
        /// </summary>
        internal static string logMsgCanShutDwn {
            get {
                return ResourceManager.GetString("logMsgCanShutDwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Can Stop = {0} .
        /// </summary>
        internal static string logMsgCanStop {
            get {
                return ResourceManager.GetString("logMsgCanStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Message received by the application .
        /// </summary>
        internal static string logMsgCmdRved {
            get {
                return ResourceManager.GetString("logMsgCmdRved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Message received by the application .
        /// </summary>
        internal static string logMsgCmdRved_ {
            get {
                return ResourceManager.GetString("logMsgCmdRved ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Can Pause and Continue = {0} .
        /// </summary>
        internal static string logMsgPauseCont {
            get {
                return ResourceManager.GetString("logMsgPauseCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il servizio è passaqto in stato di pausa.
        /// </summary>
        internal static string logMsgServicePaused {
            get {
                return ResourceManager.GetString("logMsgServicePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il servizio è ritornato attivo.
        /// </summary>
        internal static string logMsgServiceRunning {
            get {
                return ResourceManager.GetString("logMsgServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Status = {0} .
        /// </summary>
        internal static string logMsgSrvcStatus {
            get {
                return ResourceManager.GetString("logMsgSrvcStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SERVICE STARTED .
        /// </summary>
        internal static string logMsgSrvStarted {
            get {
                return ResourceManager.GetString("logMsgSrvStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Starting thread in progress.
        /// </summary>
        internal static string logMsgStartThread {
            get {
                return ResourceManager.GetString("logMsgStartThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a waiting 1000 msec before to start the service .
        /// </summary>
        internal static string logMsgWaitStart {
            get {
                return ResourceManager.GetString("logMsgWaitStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I received {0} {1}.
        /// </summary>
        internal static string sktErrRecive {
            get {
                return ResourceManager.GetString("sktErrRecive", resourceCulture);
            }
        }
    }
}
